"""
data.py – Download the SemEval-2026 Task 13 dataset from Kaggle.

Prerequisites
-------------
1. Generate a Kaggle API token at https://www.kaggle.com/settings
   and place the resulting kaggle.json in ~/.kaggle/  (Linux/macOS)
   or %USERPROFILE%\\.kaggle\\  (Windows), or set the KAGGLE_USERNAME
   and KAGGLE_KEY variables in the .env file (generated by prepare.sh).

Usage
-----
    python data.py [--dataset <kaggle-dataset-slug>] [--dest <output-dir>]
"""

import argparse
import os
import zipfile
from pathlib import Path

from dotenv import load_dotenv

# Load credentials from .env if present
load_dotenv()

KAGGLE_USERNAME = os.getenv("KAGGLE_USERNAME")
KAGGLE_KEY = os.getenv("KAGGLE_KEY")

# Inject credentials into the environment so the kaggle library picks them up
if KAGGLE_USERNAME and KAGGLE_KEY:
    os.environ["KAGGLE_USERNAME"] = KAGGLE_USERNAME
    os.environ["KAGGLE_KEY"] = KAGGLE_KEY


DEFAULT_DATASET = "gugofboat/semeval-2026-task-13"
DEFAULT_DEST = Path(__file__).parent / "data"


def download_dataset(dataset: str, dest: Path) -> None:
    """Download a Kaggle dataset and unzip it into *dest*."""
    try:
        import kaggle  # noqa: F401 – triggers credential check on import
        from kaggle.api.kaggle_api_extended import KaggleApiExtended
    except ImportError as exc:
        raise SystemExit(
            "The 'kaggle' package is not installed. "
            "Run:  pip install kaggle  or use the provided environment.yml."
        ) from exc

    api = KaggleApiExtended()
    api.authenticate()

    dest.mkdir(parents=True, exist_ok=True)
    print(f"Downloading dataset '{dataset}' to '{dest}' …")
    api.dataset_download_files(dataset, path=str(dest), unzip=False, quiet=False)

    # Unzip any downloaded archives
    for zip_path in dest.glob("*.zip"):
        print(f"Extracting {zip_path.name} …")
        with zipfile.ZipFile(zip_path, "r") as zf:
            zf.extractall(dest)
        zip_path.unlink()

    print("Download complete.")


def main() -> None:
    parser = argparse.ArgumentParser(description="Download the SemEval-2026 Task 13 dataset.")
    parser.add_argument(
        "--dataset",
        default=DEFAULT_DATASET,
        help=f"Kaggle dataset slug (default: {DEFAULT_DATASET})",
    )
    parser.add_argument(
        "--dest",
        type=Path,
        default=DEFAULT_DEST,
        help=f"Destination directory (default: {DEFAULT_DEST})",
    )
    args = parser.parse_args()

    download_dataset(args.dataset, args.dest)


if __name__ == "__main__":
    main()
