#!/usr/bin/env bash
# prepare.sh – Setup automation script
# Creates the project folder structure, sets up the Conda environment,
# and generates the .env file with Kaggle credentials.

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ── 1. Folder structure ──────────────────────────────────────────────────────
echo "[1/3] Creating project directory structure..."

mkdir -p "$PROJECT_ROOT/data"
mkdir -p "$PROJECT_ROOT/img/img_TaskA"
mkdir -p "$PROJECT_ROOT/info_dataset"
mkdir -p "$PROJECT_ROOT/src/src_TaskA"
mkdir -p "$PROJECT_ROOT/src/src_TaskB"
mkdir -p "$PROJECT_ROOT/src/src_TaskC"

echo "      Directory structure ready."

# ── 2. Conda environment ─────────────────────────────────────────────────────
echo "[2/3] Setting up Conda environment from environment.yml..."

if conda env list | grep -q "^semeval2026"; then
    echo "      Environment 'semeval2026' already exists – updating..."
    conda env update -n semeval2026 -f "$PROJECT_ROOT/environment.yml" --prune
else
    conda env create -f "$PROJECT_ROOT/environment.yml"
fi

echo "      Conda environment 'semeval2026' is ready."
echo "      Activate with:  conda activate semeval2026"

# ── 3. .env file ─────────────────────────────────────────────────────────────
echo "[3/3] Generating .env file..."

ENV_FILE="$PROJECT_ROOT/.env"

if [ -f "$ENV_FILE" ]; then
    echo "      .env already exists – skipping generation."
else
    # Prompt for Kaggle credentials
    read -rp "      Enter your Kaggle username: " KAGGLE_USERNAME
    read -rsp "      Enter your Kaggle API key:  " KAGGLE_KEY
    echo

    cat > "$ENV_FILE" <<EOF
# Auto-generated by prepare.sh – DO NOT commit this file
KAGGLE_USERNAME=${KAGGLE_USERNAME}
KAGGLE_KEY=${KAGGLE_KEY}
EOF

    chmod 600 "$ENV_FILE"
    echo "      .env file created."
fi

echo
echo "Setup complete! Run 'conda activate semeval2026' and then 'python data.py' to download the dataset."
